---
apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-config
  namespace: helloworld
data:
  config.yaml: |-
    admin:
      port: 9990
    namers:
      - kind: io.l5d.k8s
      - kind: io.l5d.k8s
        prefix: /io.l5d.k8s.http
        transformers:
          - kind: io.l5d.port
            port: 4141
    routers:
      - protocol: http
        httpAccessLog: /dev/stdout
        label: http-incoming
        servers:
          - port: 4140
            ip: 0.0.0.0
        dtab: |-
          /svc => /#/io.l5d.k8s.http/helloworld/http
      - protocol: http
        httpAccessLog: /dev/stdout
        label: http-outgoing
        servers:
          - port: 4141
            ip: 0.0.0.0
        dtab: |-
          /svc => /#/io.l5d.k8s/helloworld/http
        interpreter:
          kind: default
          transformers:
            - kind: io.l5d.k8s.localnode
