---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: world
  labels:
    app: world
    linkerd: sidecar
  namespace: helloworld
spec:
  replicas: 1
  template:
    metadata:
      name: world
      labels:
        app: world
        linkerd: sidecar
    spec:
      volumes:
        - name: linkerd-config
          configMap:
            name: linkerd-config
      containers:
        - name: helloworld
          image: buoyantio/helloworld:latest
          args:
            - "-text"
            - "world"
        - name: linkerd
          image: buoyantio/linkerd:latest
          volumeMounts:
            - name: linkerd-config
              mountPath: /etc/linkerd
              readOnly: true
          args:
            - /etc/linkerd/config.yaml
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
        - name: kubectl
          image: buoyantio/kubectl:v1.4.0
          args:
            - "proxy"
            - "-p"
            - "8001"
---
apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: helloworld
spec:
  type: NodePort
  selector:
    app: world
  ports:
    - port: 7777
      name: http
    - port: 9990
      name: linkerd-admin
